# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ca93695dcda9975fb1fd1e7be4134b8"
name = "Ai Agent 2"
application_url = "https://ai-agent-storefront.onrender.com"
embedded = true
handle = "shop-chat-agent"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_bulk_operations,unauthenticated_read_bundles,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_read_shop_pay_installments_pricing,unauthenticated_write_bulk_operations,unauthenticated_write_checkouts,unauthenticated_write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
                       
[pos]
embedded = false

[customer_authentication]
redirect_uris = [ "https://ai-agent-storefront.onrender.com/callback" ]
